[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:mongodb]
command=/usr/bin/mongod --bind_ip 0.0.0.0 --port 27017 --dbpath /data/db --logpath /var/log/mongodb/mongod.log --logappend
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/mongodb.err.log
stdout_logfile=/var/log/supervisor/mongodb.out.log
priority=1

[program:spring-boot]
command=/bin/bash -c "sleep 10 && /usr/bin/java -jar /testbed/fitnesspal/target/fitness-tracking-app-0.0.1-SNAPSHOT.jar"
directory=/testbed/fitnesspal
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/spring-boot.err.log
stdout_logfile=/var/log/supervisor/spring-boot.out.log
priority=2
startsecs=5
startretries=3
